name: Sync Daily Data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  # this string has quotes because '*' is a special character in YAML
  - cron: '0 9 * * *'  # Every day at 9:00
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies with uv
        run: uv sync --group sync-data

      - name: Sync data
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: uv run data-sync
